[Colors] Replace ComboBox with SelectorBar
microsoft/WinUI-Gallery pull request #1496
Opened 2024-03-13 17:37 UTC by niels9001

Replacing the ComboBox with the SelectorBar so it's easier to see all the different categories of colors and immediately jump to those.

![image](https://github.com/microsoft/WinUI-Gallery/assets/9866362/b7897c73-e155-486e-a272-1fced1c0683d)

2024-03-16 16:15 UTC, Jay-o-Way commented
Link #1462

2024-03-16 17:03 UTC, Jay-o-Way requested changes
Ideally, navigation elements would be placed at the very top (where the **Documentation** and **Source** controls are at the moment) and be within reach at all times. That is, not inside of a Scrollviewer. Moving those controls would be a different thread, though.

2024-03-18 15:23 UTC, niels9001 commented on WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml.cs
> +            switch (currentSelectedIndex)
Fixed!

2024-03-18 15:23 UTC, niels9001 commented on WinUIGallery/ControlPages/DesignGuidance/ColorsPage.xaml
> +            <Paragraph />
Tweaked. We need a bit more whitespace to make sure the `SelectorBar` is clearly separated from the text and is not lost between the text and colorpalettes.

2024-03-19 19:05 UTC, marcelwgn commented on WinUIGallery/Controls/DesignGuidance/ColorSections/HighContrastSection.xaml
> +    <StackPanel Margin="0,12,0,0" Spacing="{StaticResource ColorSectionSpacing}">
Unreleated?

2024-03-19 19:05 UTC, marcelwgn commented on WinUIGallery/Controls/DesignGuidance/ColorSections/TextSection.xaml
> +        <designguidance:ColorPageExample
Unrelated?

2024-03-19 19:08 UTC, marcelwgn approved these changes

2024-03-21 23:00 UTC, karkarl commented
/azp run

2024-04-08 12:34 UTC, niels9001 commented
/azp run

2024-04-18 18:33 UTC, merged