GitHub: Update Readme for consistency
microsoft/WinUI-Gallery pull request #1555
Opened 2024-05-27 07:13 UTC by 0x5bfa

## Description

As the title.
I’m wondering why the store badge is blur while I copied from MUX repo.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2024-05-27 07:15 UTC, 0x5bfa commented
@niels9001 Hi! Is there a plan to update Dev Home repo README to have this hero?
It looks great!

2024-06-05 22:50 UTC, karkarl commented on README.md
> -[![Build Status](https://dev.azure.com/ms/microsoft-ui-xaml/_apis/build/status%2Fmicrosoft.WinUI-Gallery?branchName=main)](https://dev.azure.com/ms/microsoft-ui-xaml/_build/latest?definitionId=612&br
These badges are missing.

2024-06-05 22:51 UTC, karkarl commented on README.md
> +## ⭐️ Accompanying samples for [WinAppSDK](https://github.com/microsoft/WindowsAppSDK)
I think "Accompanying Sample App for WinUI3" needs to be the second line so that there is no confusion between the different repos.

2024-06-05 22:52 UTC, karkarl requested changes
Thanks for submitting! Please see inline comments.

2024-06-16 07:53 UTC, closed without merging